name: Test

on: [push, pull_request]

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and NPM
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: npm install
        run: |
          npm install

      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYDDD

      - name: npm test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm run package -- -c.extraMetadata.version=2.${{steps.current-time.outputs.formattedTime}}.${{github.run_number}}
          npm run lint
          npm exec tsc
          npm test
